/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-PPM_Analog_RC
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PPM_ANALOG_RC_API_H
#define INCLUDED_PPM_ANALOG_RC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_PPM_Analog_RC_EXPORTS
#define PPM_ANALOG_RC_API __GR_ATTR_EXPORT
#else
#define PPM_ANALOG_RC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PPM_ANALOG_RC_API_H */
