/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(PPM_Peak_Detector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(97cecad4b4a4221b6cb55974fb645420)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/PPM_Analog_RC/PPM_Peak_Detector.h>
// pydoc.h is automatically generated in the build directory
#include <PPM_Peak_Detector_pydoc.h>

void bind_PPM_Peak_Detector(py::module& m)
{

    using PPM_Peak_Detector    = ::gr::PPM_Analog_RC::PPM_Peak_Detector;


    py::class_<PPM_Peak_Detector, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<PPM_Peak_Detector>>(m, "PPM_Peak_Detector", D(PPM_Peak_Detector))

        .def(py::init(&PPM_Peak_Detector::make),
           py::arg("peak_threshold"),
           D(PPM_Peak_Detector,make)
        )
        



        ;




}








