/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(PPM_Modulator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3a314bf33d7709acc4208985f0b8c8dc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/PPM_Analog_RC/PPM_Modulator.h>
// pydoc.h is automatically generated in the build directory
#include <PPM_Modulator_pydoc.h>

void bind_PPM_Modulator(py::module& m)
{

    using PPM_Modulator    = ::gr::PPM_Analog_RC::PPM_Modulator;


    py::class_<PPM_Modulator, gr::block, gr::basic_block,
        std::shared_ptr<PPM_Modulator>>(m, "PPM_Modulator", D(PPM_Modulator))

        .def(py::init(&PPM_Modulator::make),
           py::arg("samp_rate"),
           D(PPM_Modulator,make)
        )
        



        ;




}








